#!/bin/bash 
file_arr=() 
while IFS = read -r line; do
  file_arr+=("$line")
done </uploads/TMA.txt
seq=1
for ((i=0; i<${#file_arr[@]}; i++ ));
do 
echo "$seq : ${file_arr[$i]}" 
seq =$((seq+1)) 
done
